workflows:
  android-apk-build:
    name: Compilación APK Android
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Reconstruir estructura nativa Android v2
        script: |
          flutter create temp_app --platforms=android --org com.viajesync.app
          rm -rf android
          cp -r temp_app/android ./android
          rm -rf temp_app
      - name: Descargar dependencias de Flutter
        script: |
          flutter pub get
      - name: Compilar APK de Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - juanpiguerra600@gmail.com
